### PR TITLE
Fixed issue of message invoking from non-UI thread

### PR DESCRIPTION
**Pull request by johnbindel**
Fixed issue of message invoking from non-UI thread. See: https://github.com/PrismLibrary/Prism/issues/878#issuecomment-306598052

### CODE REVIEW

**Comment by countincognito** [comment]
Thanks for this, sorry for the slow response. How did this issue manifest?

**Comment by johnbindel** [comment]
I experienced the issue prior to your fix: https://github.com/countincognito/Zametek.ProjectPlan/commit/f6977c5ef47085dee7301e6361618737e58e3886

You should be able to reproduce by throwing an exception within any of the update code- this will cause the error to bubble up through the UI and should repro just fine. It was throwing an InvalidOperationException because it was not invoked on the UI context.

**Comment by countincognito** [comment]
Ah, I think that InvalidOperationException was coming from the Maths library itself (I've been lazy and haven't included meaningful error messages in those yet - I will get round to it).

I tried to recreate the error you described and couldn't - the notification dialogs just popped up as expected with an empty message. None-the-less, I like the changes you've made (really nice technique), so I'm going to include it. Thanks!

**Comment by johnbindel** [comment]
Yes, you're correct- for some reason the originating IOE created a subsequent IOE when attempting to send the message to the UI. Glad you like it! (Not sure if the same exception might be encountered by other types of messages passed to the UI from an async background thread- I would expect so!).

**Comment by countincognito** [comment]
Strangely, for some reason it's not triggering the Publish when I test it. It's just halting at the waitHandle.Wait() line and never entering the handleMessage Action. Any thoughts why that might be?

**Pull request merged**
